DROP DATABASE fund ;
create DATABASE fund;
use fund;
/*
    表名格式说明
1. FU_ -> 本项目手动创建的表
2. FU_AU_ -> 本项目权限相关的表 AU(Authorization 授权)
3. FU_GE_ -> 一般（general）项目资金卡表，
  之后的 FU_RE_ -> 科研(research)  FU_PR_ -> 项目(project)
4. ACT_ -> 工作流框架 Activiti5 自动建的表，其表结构及数据不可修改，否则流程异常。

      项目约定：
1. 所有后期维护新增表结构及字段，请务必遵守上方表名格式；
2. 所有表名及字段名请使用大写，以下划线分隔；
3. 所有建表语名，请写在此 schema 文件中；
4. 对表结构或字段进行修改，请记录在 alter文件中，务必记录版本号及时间；
5.

*/
-- 创建用户登陆表，此表只记录用户登陆名及密码等信息
CREATE TABLE `FU_AU_USER_LOGIN`(
  `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
  `LOGIN_ID` VARCHAR(200) NOT NULL COMMENT '用户登录名',
  `SALT` VARCHAR(32) NOT NULL COMMENT '随机生成的盐值',
  `PASSWORD` VARCHAR(32) NOT NULL COMMENT '密码(MD5加密)',
  `ACC_STATUS` VARCHAR(32) COMMENT '账号状态',
  `USER_ID` VARCHAR(32) NOT NULL COMMENT '关联用户表',
  `AVAILABLE` VARCHAR(32) NOT NULL COMMENT '逻辑删除标识',
  `PASSWORD_UPDATE_TIME` DATETIME NOT NULL COMMENT '最近一次密码修改时间',
  `CREATE_TIME` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
  `CREATE_USER` VARCHAR(32)  COMMENT '记录创建者',
  PRIMARY KEY (`ID`),
  KEY (`LOGIN_ID`)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT '用户登陆信息数据表';

/*
系统用户详细信息数据表
*/
CREATE TABLE `FU_AU_USER`(
  `ID` VARCHAR(32) NOT NULL COMMENT '主键ID',
  `NAME` VARCHAR(50) NOT NULL COMMENT '用户名（全名）',
  `GENDER` VARCHAR(32) NOT NULL COMMENT '性别',
  `CRED_TYPE` VARCHAR(32) NOT NULL COMMENT '证件类型 CRED(credentials)证件',
  `CRED_NUM` VARCHAR(100) NOT NULL COMMENT '证件编号',
  `EMAIL` VARCHAR(100) COMMENT '邮件地址',
  `PRI_PHONE_NUM` VARCHAR(20) COMMENT '首要联系电话',
  `OHTER_TEL` VARCHAR(200) COMMENT '其他联系方式',
  `ADDRESS` VARCHAR(200) COMMENT '住址',
  `COMMENTS` VARCHAR(400) COMMENT '备注',
  `STATUS` VARCHAR(32) NOT NULL COMMENT '用户状态',
  `AVAILABLE` VARCHAR(32) NOT NULL COMMENT '逻辑删除标识',
  `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATER_USER` VARCHAR(32)  COMMENT '记录创建者',
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET = UTF8 COMMENT '用户详细信息表';

CREATE TABLE `FU_AU_ROLE`(
  `ID` VARCHAR(32) NOT NULL COMMENT '主键',
  `NAME` VARCHAR(50) NOT NULL COMMENT '角色名称',
  `CODE` VARCHAR(32) NOT NULL COMMENT '角色编码',
  `DESCRIPTION` VARCHAR(400) COMMENT '部门描述',
  `AVAILABLE` VARCHAR(32) NOT NULL COMMENT '逻辑删除标识',
  `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATER_USER` VARCHAR(32)  COMMENT '记录创建者',
  PRIMARY KEY (`ID`)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8 COMMENT '角色表';

CREATE TABLE `FU_AU_RESOURCE`(
  `ID` VARCHAR(32) NOT NULL COMMENT '主键',
  `NAME` VARCHAR(50) NOT NULL COMMENT '资源名称',
  `TYPE` VARCHAR(20) NOT NULL COMMENT '资源类型',
  `URL` VARCHAR(200) COMMENT 'URL(菜单类型的)',
  `PARENT_ID` VARCHAR(32)  COMMENT '父节点ID',
  `PERMISSION` VARCHAR(100) NOT NULL COMMENT '权限表示字符串',
  `AVAILABLE` VARCHAR(32) NOT NULL COMMENT '逻辑删除标识',
  `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATER_USER` VARCHAR(32)  COMMENT '记录创建者',
  PRIMARY KEY (`ID`)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8 COMMENT '资源表';

CREATE TABLE `FU_DEPARTMENT`(
  `ID` VARCHAR(32) NOT NULL COMMENT '主键',
  `NAME` VARCHAR(100) NOT NULL COMMENT '部门名称',
  `DESCRIPTION` VARCHAR(400) COMMENT '部门描述',
  `PARENT_ID` VARCHAR(32) COMMENT '父部门ID',
  `AVAILABLE` VARCHAR(32) NOT NULL COMMENT '逻辑删除标识',
  `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `CREATER_USER` VARCHAR(32)  COMMENT '记录创建者',
  PRIMARY KEY (`ID`)
)ENGINE=InnoDB DEFAULT CHARSET=UTF8 COMMENT '部门表';

CREATE TABLE `FU_AU_USER_ROLE`(
  `ID` VARCHAR(32) NOT NULL COMMENT '主键',
  `USER_ID` VARCHAR(32) NOT NULL COMMENT '用户ID',
  `ROLE_ID` VARCHAR(32) NOT NULL COMMENT '角色ID',
  `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
--  `CREATER_USER` VARCHAR(32)  COMMENT '记录创建者',
  PRIMARY KEY (`ID`),
  UNIQUE (`USER_ID`,`ROLE_ID`)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8 COMMENT '用户与角色关系表';

CREATE TABLE `FU_AU_ROLE_RES`(
  `ID` VARCHAR(32) NOT NULL COMMENT '主键',
  `ROLE_ID` VARCHAR(32) NOT NULL COMMENT '角色ID',
  `RES_ID` VARCHAR(32) NOT NULL COMMENT '资源ID',
  `CREATE_TIME` DATETIME DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
--  `CREATER_USER` VARCHAR(32)  COMMENT '记录创建者',
  PRIMARY KEY (`ID`),
  UNIQUE (`ROLE_ID`,`RES_ID`)
)ENGINE = InnoDB DEFAULT CHARSET = UTF8 COMMENT '角色与资源关系表';

